# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to npm

# This workFlow is Trigger To Publish NPM Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type to bump (patch, minor, major)'
        required: true
        default: 'patch'

# Auto publish on push to main
#  push:
#    branches:
#      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm
        run: |
          cd ./second_test/lucas-cli-test/
          npm install

      - name: Install dependencies
        run: |
          cd ./second_test/lucas-cli-test/
          npm ci

      - name: Npm Version Patch
        run: |
          cd ./second_test/lucas-cli-test/
          npm version ${{ github.event.inputs.version }}

      - name: Git Commit
        run: |
          git config --global user.name "swings134man"
          git add .
          git commit -m "Bump Version"
          
      - name: Publish to npm
        run: |
          cd ./second_test/lucas-cli-test/
          npm publish --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}


      - name: git push
        run: git push origin main
